#!/bin/bash

set -o errexit
set -o nounset

mkdir -p run
mkdir -p gcode

stop_container() {
  local what=$1
  if docker stop ${what}; then
    CONTAINER_ID=$(docker ps --filter status=exited | awk -v what=${what} '{ if (index($2, what) != 0) print $1}')
    docker rm $CONTAINER_ID
  fi
}


# --- KLIPPER ---

DOCKERFILE_PATH=./prind/docker/klipper/
#DOCKER_LABEL=mkuf/klipper:latest
DOCKER_LABEL=michal/klipper
DOCKER_TARGET=build-simulavr
start_klippy() {
  # Using target 'run' for actual printer connection.
  docker build \
    -t michal/klipper \
    --target $DOCKER_TARGET \
    $DOCKERFILE_PATH

  docker run \
    --privileged \
    --name klipper \
    -v /dev:/dev \
    -v $(pwd)/run:/opt/printer_data/run \
    -v $(pwd)/gcode:/opt/printer_data/gcodes \
    -v $(pwd)/printer.cfg:/opt/printer_data/config/printer.cfg \
    michal/klipper
}

stop_klippy() {
  echo "Stopping Klipper!"
  stop_container "klipper"
}

# --- MOONRAKER ---

start_moonraker() {
  # without privileged I'm getting python thread errors
  docker run \
    --privileged \
    --name moonraker \
    -v $(pwd)/run:/opt/printer_data/run \
    -v $(pwd)/gcode:/opt/printer_data/gcodes \
    -v $(pwd)/moonraker.conf:/opt/printer_data/config/moonraker.conf \
    -p 7125:7125 \
    mkuf/moonraker:latest
}

stop_moonraker() {
  echo "Stopping Moonraker!"
  stop_container "moonraker"
}

"$@"
